In [1]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [2]:
np.ndim(A) # 配列の次元数

1

In [3]:
A.shape # 配列の形状

(4,)

In [4]:
A.shape[0]

4

In [5]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.ndim(B)

2

In [7]:
B.shape

(3, 2)

In [8]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [9]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [10]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [14]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [15]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [16]:
X = np.array([1, 2])
X.shape

(2,)

In [17]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [18]:
W.shape

(2, 3)

In [19]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


In [20]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [21]:
W1.shape

(2, 3)

In [22]:
X.shape

(2,)

In [23]:
B1.shape

(3,)

In [24]:
A1 = np.dot(X, W1) + B1

In [25]:
print(A1)

[0.3 0.7 1.1]


In [27]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [28]:
Z1 = sigmoid(A1)
print(Z1)

[0.57444252 0.66818777 0.75026011]


In [30]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [31]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [32]:
print(Z2)

[0.62624937 0.7710107 ]


In [33]:
def identity_function(x):
    return x

In [34]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

In [37]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y


network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


In [38]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)

In [39]:
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [40]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [41]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [42]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

/home/ymt/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [43]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [44]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [45]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [46]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [47]:
np.sum(y)

1.0